### ISSUE TITLE
incompatible types: int[] cannot be converted to int n

### ISSUE THREAD

**Issue by pawarashish564** [pawarashish564/AutoCompiler#12]
For this error we need to convert 

```java
int n = new int[10]; 
```

into 

```java 
int n[] = new int[10];
```

> But autocompiler just writes second char as 'n'

**Comment by pawarashish564** [comment]
I'm thinking following way for doing it 
```java
//get all the errors which are not expected errors.
List<Tuple<String>> otherErrors = list.stream()
        .filter(e -> !e.getThird().endsWith("expected")) 
        .sorted(Comparator.comparing(Tuple::getSecond))
        .collect(Collectors.toList());
    // then manually handle them
        for (Tuple<String> tuple : otherErrors) {
            
            String error  = tuple.getThird();
            if(error.equals("incompatible types: int[] cannot be converted to int n"))
            {
                //manually handle the case when square bracket is missing
            }
        }

```

**Comment by pawarashish564** [comment]
@tauseefansari  Any Ideas ?

**Comment by tauseefansari** [comment]
I have tried to replace n with new int[] and try with a new file 

But it won't works for me 😔

**Comment by pawarashish564** [comment]
We need to handle it manually ! so parse the line then put the `[]` then it will work .

**Comment by pawarashish564** [comment]
I have solved it . 

>Steps I have done 
- RandomReader class which return nth line from the file (thanks to @tauseefansari )
- RandomWriter class with a method to write at nth line in file
- comment the error line (@Afif79 )
- append the [] to stringBuffer .insert then writer the line to the original source file.



Solved !

**Comment by pawarashish564** [comment]
See my latest commit
